name: React Native Staging CI/CD

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint ./src
        continue-on-error: true # Ignore lint errors for now, to allow the workflow to continue

      - name: Type check
        run: npm run typecheck

#  build-android:
#    name: Build Android
#    needs: lint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'npm'
#
#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#
#        # Validate Gradle wrapper to prevent build tool attack
#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@v1
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Build Android
#        run: |
#          cd android
#          ./gradlew assembleDebug
#
#      - name: Upload APK artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-android
#          path: |
#            # Add more if you have aab, mapping files, etc.
#            # android/app/build/outputs/bundle/debug/app-debug.aab
#            android/app/build/outputs/apk/debug/app-debug.apk
#          retention-days: 5

  build-ios:
    name: Build iOS
    needs: lint
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Switch to Xcode 16 so that it can build with Expo 53
      - name: Setup Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # Since I do not have an Apple Developer account, I will not be able to sign the app.
      # This job will build the unsigned ios app, but still need to sign it before it can be distributed or install
      - name: Build unsigned iOS
        run: |
          cd ios
          xcodebuild build -workspace RytTransfer.xcworkspace -scheme RytTransfer -configuration Debug -sdk iphonesimulator -derivedDataPath ./
          
          # Create Payload folder and move .app file
          mkdir payload
          cp -R "./build/Products/Debug-iphoneos/RytTransfer.app" "./payload"
          
          #  Zip the Payload folder and rename to .ipa
          zip -r "RytTransfer.ipa" "./payload"

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ios
          path: |
            # Add more if you have .ipa, dSYM files, etc.
            RytTransfer.ipa
          retention-days: 5
