name: React Native CI/CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint ./src
        continue-on-error: true

      - name: Type check
        run: npm run typecheckç

  build-android:
    name: Build Android
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo and EAS
        run: npm install -g expo-cli eas-cli

      - name: Build APK with EAS
        run: eas build --platform android --non-interactive --local
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-android
          path: build/android/app-release.apk
          retention-days: 5

  build-ios:
    name: Build iOS
    needs: lint-and-test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo and EAS
        run: npm install -g expo-cli eas-cli

      - name: Build iOS with EAS
        run: eas build --platform ios --non-interactive --local
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-ios
          path: build/ios/
          retention-days: 5
